"""Logbook entry editor.

Build a per-day `entries[]` list for the logbook auto-fill console script,
then export a ready-to-paste script.js (also copied to clipboard).

Run:
    python logbook_ui.py
"""

from __future__ import annotations

import datetime
import json
import sys
import tkinter as tk
from pathlib import Path
from tkinter import filedialog, messagebox, ttk

import openpyxl

DEFAULT_IN_TIME = "09:00"
DEFAULT_OUT_TIME = "05:00"
DEFAULT_IN_AMPM = "am"
DEFAULT_OUT_AMPM = "pm"
AMPM = ["am", "pm"]

WEEKDAYS = ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"]

# Company timesheet layout: data rows start at row 14, with NO/DAY/DATE/TASK/
# PROJECT NAME/DETAIL/S-O NO/IN/OUT/TOTAL in columns A-J.
TIMESHEET_DATA_START_ROW = 14
COL_NO = 1
COL_DAY = 2
COL_TASK = 4
COL_DETAIL = 6
COL_IN = 8
COL_OUT = 9


def _is_zero_time(value: object) -> bool:
    """True for empty cells and 0:00-style values (non-working days)."""
    if value is None:
        return True
    if isinstance(value, datetime.time):
        return value.hour == 0 and value.minute == 0
    text = str(value).strip()
    return text in ("", "0", "0:00", "00:00", "0:00:00")


def parse_timesheet_excel(path: str) -> tuple[str, list[dict[str, str] | None]]:
    """Read the company timesheet .xlsx and return (start_weekday, entries).

    entries follows the same shape as Row.to_entry(): None for an Off day,
    otherwise a dict with default clock times and Task/Detail mapped to
    Activity/Description.
    """
    wb = openpyxl.load_workbook(path, data_only=True)
    ws = wb.active

    entries: list[dict[str, str] | None] = []
    start_weekday = ""
    row = TIMESHEET_DATA_START_ROW
    while True:
        no_val = ws.cell(row=row, column=COL_NO).value
        if no_val is None or str(no_val).strip() == "":
            break

        day_val = ws.cell(row=row, column=COL_DAY).value
        weekday = str(day_val).strip()[:3].title() if day_val else ""
        if not start_weekday and weekday in WEEKDAYS:
            start_weekday = weekday

        in_val = ws.cell(row=row, column=COL_IN).value
        out_val = ws.cell(row=row, column=COL_OUT).value
        if _is_zero_time(in_val) and _is_zero_time(out_val):
            entries.append(None)
        else:
            task_val = ws.cell(row=row, column=COL_TASK).value
            detail_val = ws.cell(row=row, column=COL_DETAIL).value
            entries.append({
                "editClockIn": join_time(DEFAULT_IN_TIME, DEFAULT_IN_AMPM),
                "editClockOut": join_time(DEFAULT_OUT_TIME, DEFAULT_OUT_AMPM),
                "editActivity": str(task_val).strip() if task_val else "",
                "editDescription": str(detail_val).strip() if detail_val else "",
            })
        row += 1

    return start_weekday or "Mon", entries


def split_time(value: str) -> tuple[str, str]:
    """'09:00 am' -> ('09:00', 'am'). Tolerant of missing/odd suffix."""
    parts = value.strip().rsplit(" ", 1)
    if len(parts) == 2 and parts[1].lower() in AMPM:
        return parts[0], parts[1].lower()
    return value.strip(), DEFAULT_IN_AMPM


def join_time(time_str: str, ampm: str) -> str:
    """('09:00', 'am') -> '09:00 am'."""
    return f"{time_str.strip()} {ampm}"


SCRIPT_TEMPLATE = """\
// =====================================================================
// LOGBOOK AUTO-FILL — generated by logbook_ui.py
// Paste this whole block into the browser console on the logbook page.
//   object -> fill row | null -> OFF day
// =====================================================================

const entries = {entries_json};

// =====================================================================
// One combined array, in document order = day order. Blue (empty) and orange
// (filled) day buttons both carry `.detailsbtn`, so this keeps index i aligned
// to day i regardless of color. Clicking a button edits that day whether it was
// blue or orange -> filling a filled day just overwrites it (auto-override).
const buttons = Array.from(document.querySelectorAll('.detailsbtn'));

buttons.forEach((b, i) => {{
    const entry = entries[i];

    if (entry && entry.skip) return; // leave this day untouched

    const editClockIn = document.getElementById('editClockIn');
    const editClockOut = document.getElementById('editClockOut');
    const editActivity = document.getElementById('editActivity');
    const editDescription = document.getElementById('editDescription');
    const submit = document.querySelector(
        '.button.button-primary[onclick="editSaveClick()"]'
    );
    const off = document.querySelector(
        '.button.button-primary[onclick="OffClick()"]'
    );
    b.click();

    if (entry === null || entry === undefined) {{
        off.click();
        submit.click();
        return;
    }}

    editClockIn.value = entry.editClockIn;
    editClockOut.value = entry.editClockOut;
    editActivity.value = entry.editActivity;
    editDescription.value = entry.editDescription;
    submit.click();
}});
"""


class Row:
    """One logbook day = one editable row of widgets."""

    def __init__(self, parent: tk.Widget, index: int, app: "App") -> None:
        self.app = app
        self.index = index
        self.weekday = ""

        self.off_var = tk.BooleanVar(value=False)
        self.skip_var = tk.BooleanVar(value=False)
        self.in_time = tk.StringVar(value=DEFAULT_IN_TIME)
        self.in_ampm = tk.StringVar(value=DEFAULT_IN_AMPM)
        self.out_time = tk.StringVar(value=DEFAULT_OUT_TIME)
        self.out_ampm = tk.StringVar(value=DEFAULT_OUT_AMPM)

        self.day_label = ttk.Label(parent, width=10, anchor="w")
        self.off_chk = ttk.Checkbutton(
            parent, variable=self.off_var, command=self._on_off
        )
        self.skip_chk = ttk.Checkbutton(
            parent, variable=self.skip_var, command=self._on_skip
        )

        self.in_frame, self.in_widgets = self._time_cell(
            parent, self.in_time, self.in_ampm
        )
        self.out_frame, self.out_widgets = self._time_cell(
            parent, self.out_time, self.out_ampm
        )
        self.activity_e = tk.Text(
            parent, width=28, height=3, wrap="word", relief="solid", borderwidth=1,
            font=("TkDefaultFont", 9),
        )
        self.description_e = tk.Text(
            parent, width=34, height=3, wrap="word", relief="solid", borderwidth=1,
            font=("TkDefaultFont", 9),
        )
        for text_widget in (self.activity_e, self.description_e):
            text_widget.bind("<MouseWheel>", app.forward_mousewheel)
            text_widget.bind("<Button-4>", app.forward_mousewheel)
            text_widget.bind("<Button-5>", app.forward_mousewheel)

        self.widgets = [
            self.day_label,
            self.off_chk,
            self.skip_chk,
            self.in_frame,
            self.out_frame,
            self.activity_e,
            self.description_e,
        ]

    @staticmethod
    def _time_cell(
        parent: tk.Widget, time_var: tk.StringVar, ampm_var: tk.StringVar
    ) -> tuple[ttk.Frame, list[tk.Widget]]:
        frame = ttk.Frame(parent)
        entry = ttk.Entry(frame, textvariable=time_var, width=7)
        entry.pack(side="left")
        combo = ttk.Combobox(
            frame, textvariable=ampm_var, values=AMPM, width=4, state="readonly"
        )
        combo.pack(side="left", padx=(2, 0))
        return frame, [entry, combo]

    def grid(self, row: int) -> None:
        for col, w in enumerate(self.widgets):
            w.grid(row=row, column=col, padx=3, pady=2, sticky="w")

    def set_day_label(self, text: str) -> None:
        self.day_label.config(text=text)

    def get_activity(self) -> str:
        return self.activity_e.get("1.0", "end-1c")

    def set_activity(self, text: str) -> None:
        state = self.activity_e.cget("state")
        self.activity_e.config(state="normal")
        self.activity_e.delete("1.0", "end")
        self.activity_e.insert("1.0", text)
        self.activity_e.config(state=state)

    def get_description(self) -> str:
        return self.description_e.get("1.0", "end-1c")

    def set_description(self, text: str) -> None:
        state = self.description_e.cget("state")
        self.description_e.config(state="normal")
        self.description_e.delete("1.0", "end")
        self.description_e.insert("1.0", text)
        self.description_e.config(state=state)

    def _on_off(self) -> None:
        disabled = self.off_var.get()
        for w in (self.activity_e, self.description_e):
            w.config(state="disabled" if disabled else "normal")
        for w in self.in_widgets + self.out_widgets:
            if isinstance(w, ttk.Combobox):
                w.config(state="disabled" if disabled else "readonly")
            else:
                w.config(state="disabled" if disabled else "normal")

    def lock_sunday(self) -> None:
        """Force this row OFF and lock its flags (Sundays have no site button)."""
        self.off_var.set(True)
        self.skip_var.set(False)
        self._on_off()  # disable the data fields
        self.off_chk.config(state="disabled")
        self.skip_chk.config(state="disabled")

    def _on_skip(self) -> None:
        if self.skip_var.get():
            # skip disables everything else on the row
            self.off_chk.config(state="disabled")
            for w in (self.activity_e, self.description_e):
                w.config(state="disabled")
            for w in self.in_widgets + self.out_widgets:
                w.config(state="disabled")
        else:
            self.off_chk.config(state="normal")
            self._on_off()

    def to_entry(self) -> dict[str, str] | None:
        if self.skip_var.get():
            return {"skip": True}
        if self.off_var.get():
            return None
        return {
            "editClockIn": join_time(self.in_time.get(), self.in_ampm.get()),
            "editClockOut": join_time(self.out_time.get(), self.out_ampm.get()),
            "editActivity": self.get_activity(),
            "editDescription": self.get_description(),
        }

    def load(self, entry: dict[str, str] | None) -> None:
        if entry is None:
            self.off_var.set(True)
            self.skip_var.set(False)
            self._on_skip()
            return
        if entry.get("skip"):
            self.off_var.set(False)
            self.skip_var.set(True)
            self._on_skip()
            return
        self.off_var.set(False)
        self.skip_var.set(False)
        self._on_skip()
        it, ia = split_time(entry.get("editClockIn", DEFAULT_IN_TIME))
        ot, oa = split_time(entry.get("editClockOut", DEFAULT_OUT_TIME))
        self.in_time.set(it)
        self.in_ampm.set(ia)
        self.out_time.set(ot)
        self.out_ampm.set(oa)
        self.set_activity(entry.get("editActivity", ""))
        self.set_description(entry.get("editDescription", ""))


class App:
    def __init__(self, root: tk.Tk) -> None:
        self.root = root
        root.title("Logbook Entry Editor")
        self.rows: list[Row] = []

        self._build_toolbar()
        self._build_table()
        self._build_footer()

        self.rebuild_rows()

    # ---- UI construction -------------------------------------------------
    def _build_toolbar(self) -> None:
        bar = ttk.Frame(self.root, padding=8)
        bar.pack(fill="x")

        ttk.Label(bar, text="Days:").pack(side="left")
        self.days_var = tk.IntVar(value=28)
        ttk.Spinbox(
            bar, from_=1, to=31, textvariable=self.days_var, width=5
        ).pack(side="left", padx=(2, 10))

        ttk.Label(bar, text="Start weekday:").pack(side="left")
        self.start_var = tk.StringVar(value="Mon")
        ttk.Combobox(
            bar, textvariable=self.start_var, values=WEEKDAYS, width=6,
            state="readonly",
        ).pack(side="left", padx=(2, 10))

        ttk.Button(bar, text="Rebuild rows", command=self.rebuild_rows).pack(
            side="left", padx=4
        )

        # ---- bulk clock-time setter ----
        bulk = ttk.LabelFrame(self.root, text="Set all time", padding=8)
        bulk.pack(fill="x", padx=8, pady=(0, 8))

        ttk.Label(bulk, text="In:").pack(side="left")
        self.bulk_in_time = tk.StringVar(value=DEFAULT_IN_TIME)
        ttk.Entry(bulk, textvariable=self.bulk_in_time, width=7).pack(
            side="left", padx=(2, 2)
        )
        self.bulk_in_ampm = tk.StringVar(value=DEFAULT_IN_AMPM)
        ttk.Combobox(
            bulk, textvariable=self.bulk_in_ampm, values=AMPM, width=4,
            state="readonly",
        ).pack(side="left", padx=(0, 10))

        ttk.Label(bulk, text="Out:").pack(side="left")
        self.bulk_out_time = tk.StringVar(value=DEFAULT_OUT_TIME)
        ttk.Entry(bulk, textvariable=self.bulk_out_time, width=7).pack(
            side="left", padx=(2, 2)
        )
        self.bulk_out_ampm = tk.StringVar(value=DEFAULT_OUT_AMPM)
        ttk.Combobox(
            bulk, textvariable=self.bulk_out_ampm, values=AMPM, width=4,
            state="readonly",
        ).pack(side="left", padx=(0, 10))

        ttk.Button(bulk, text="Apply times to all", command=self.apply_clock_all).pack(
            side="left", padx=4
        )

        # ---- bulk activity / description setter ----
        bulk2 = ttk.LabelFrame(self.root, text="Set all text", padding=8)
        bulk2.pack(fill="x", padx=8, pady=(0, 8))

        ttk.Label(bulk2, text="Activity:").pack(side="left")
        self.bulk_activity = tk.StringVar(value="")
        ttk.Entry(bulk2, textvariable=self.bulk_activity, width=34).pack(
            side="left", padx=(2, 10)
        )
        ttk.Label(bulk2, text="Description:").pack(side="left")
        self.bulk_description = tk.StringVar(value="")
        ttk.Entry(bulk2, textvariable=self.bulk_description, width=40).pack(
            side="left", padx=(2, 10)
        )
        ttk.Button(
            bulk2, text="Apply text to all", command=self.apply_text_all
        ).pack(side="left", padx=4)

        # ---- subheader prepend ----
        bulk3 = ttk.LabelFrame(self.root, text="Add subheader", padding=8)
        bulk3.pack(fill="x", padx=8, pady=(0, 8))

        ttk.Label(bulk3, text="Subheader:").pack(side="left")
        self.subheader_var = tk.StringVar(value="")
        ttk.Entry(bulk3, textvariable=self.subheader_var, width=30).pack(
            side="left", padx=(2, 10)
        )
        ttk.Label(bulk3, text="From day:").pack(side="left")
        self.subheader_from_var = tk.IntVar(value=1)
        ttk.Spinbox(
            bulk3, from_=1, to=31, textvariable=self.subheader_from_var, width=5
        ).pack(side="left", padx=(2, 10))
        ttk.Label(bulk3, text="To day:").pack(side="left")
        self.subheader_to_var = tk.IntVar(value=1)
        ttk.Spinbox(
            bulk3, from_=1, to=31, textvariable=self.subheader_to_var, width=5
        ).pack(side="left", padx=(2, 10))
        ttk.Button(
            bulk3, text="Apply subheader", command=self.apply_subheader
        ).pack(side="left", padx=4)

    def _build_table(self) -> None:
        # scrollable canvas holding the grid
        container = ttk.Frame(self.root)
        container.pack(fill="both", expand=True, padx=8)

        canvas = tk.Canvas(container, highlightthickness=0)
        vbar = ttk.Scrollbar(container, orient="vertical", command=canvas.yview)
        self.grid_frame = ttk.Frame(canvas)

        self.grid_frame.bind(
            "<Configure>",
            lambda e: canvas.configure(scrollregion=canvas.bbox("all")),
        )
        canvas.create_window((0, 0), window=self.grid_frame, anchor="nw")
        canvas.configure(yscrollcommand=vbar.set)
        canvas.pack(side="left", fill="both", expand=True)
        vbar.pack(side="right", fill="y")

        self.canvas = canvas
        canvas.bind_all("<MouseWheel>", self.forward_mousewheel)
        # X11 (Linux) sends Button-4/5 wheel events instead of <MouseWheel>
        canvas.bind_all("<Button-4>", self.forward_mousewheel)
        canvas.bind_all("<Button-5>", self.forward_mousewheel)

        headers = ["Day", "Off", "Skip", "Clock In", "Clock Out",
                   "Activity", "Description"]
        for col, h in enumerate(headers):
            ttk.Label(self.grid_frame, text=h, font=("", 9, "bold")).grid(
                row=0, column=col, padx=3, pady=4, sticky="w"
            )

    def _build_footer(self) -> None:
        bar = ttk.Frame(self.root, padding=8)
        bar.pack(fill="x")
        ttk.Button(bar, text="Load JSON…", command=self.load_json).pack(
            side="left", padx=4
        )
        ttk.Button(bar, text="Save JSON…", command=self.save_json).pack(
            side="left", padx=4
        )
        ttk.Button(bar, text="Import Excel…", command=self.import_excel).pack(
            side="left", padx=4
        )
        ttk.Button(bar, text="Reset All", command=self.reset_all).pack(
            side="left", padx=4
        )
        ttk.Button(
            bar, text="Generate script.js + copy", command=self.generate
        ).pack(side="right", padx=4)

    # ---- row management --------------------------------------------------
    def rebuild_rows(self) -> None:
        # preserve existing values where possible
        old = [r.to_entry() for r in self.rows]
        for r in self.rows:
            for w in r.widgets:
                w.destroy()
        self.rows.clear()

        n = max(1, self.days_var.get())
        start = WEEKDAYS.index(self.start_var.get())
        for i in range(n):
            row = Row(self.grid_frame, i, self)
            wd = WEEKDAYS[(start + i) % 7]
            row.weekday = wd
            row.set_day_label(f"{i + 1:>2}  {wd}")
            row.grid(i + 1)
            if i < len(old):
                row.load(old[i])
            self.rows.append(row)
        self._lock_sundays()

    def _lock_sundays(self) -> None:
        for row in self.rows:
            if row.weekday == "Sun":
                row.lock_sunday()

    def forward_mousewheel(self, event: tk.Event) -> str:
        """Scroll the row table on any mouse wheel event, even over a Text box.

        macOS reports small per-notch deltas (no /120 scaling like Windows),
        so the two platforms need different unit conversions.
        """
        if event.num == 4:
            self.canvas.yview_scroll(-3, "units")
        elif event.num == 5:
            self.canvas.yview_scroll(3, "units")
        elif sys.platform == "darwin":
            self.canvas.yview_scroll(int(-event.delta), "units")
        else:
            self.canvas.yview_scroll(int(-event.delta / 120), "units")
        return "break"

    def apply_clock_all(self) -> None:
        """Set clock in/out on every non-off row to the bulk values."""
        for row in self.rows:
            if row.off_var.get() or row.skip_var.get():
                continue
            row.in_time.set(self.bulk_in_time.get())
            row.in_ampm.set(self.bulk_in_ampm.get())
            row.out_time.set(self.bulk_out_time.get())
            row.out_ampm.set(self.bulk_out_ampm.get())

    def reset_all(self) -> None:
        """Restore every row to defaults (times + activity/description, clear flags)."""
        if not messagebox.askyesno(
            "Reset All",
            "Reset every row's clock times and activity/description to defaults "
            "and clear all Off/Skip flags?\n\nThis cannot be undone.",
        ):
            return
        for row in self.rows:
            row.off_var.set(False)
            row.skip_var.set(False)
            row.in_time.set(DEFAULT_IN_TIME)
            row.in_ampm.set(DEFAULT_IN_AMPM)
            row.out_time.set(DEFAULT_OUT_TIME)
            row.out_ampm.set(DEFAULT_OUT_AMPM)
            row.set_activity("")
            row.set_description("")
            row._on_skip()  # re-enable fields (clears off/skip disabling)
        self._lock_sundays()

    def apply_text_all(self) -> None:
        """Set activity/description on every non-off row to the bulk values."""
        for row in self.rows:
            if row.off_var.get() or row.skip_var.get():
                continue
            row.set_activity(self.bulk_activity.get())
            row.set_description(self.bulk_description.get())

    def apply_subheader(self) -> None:
        """Prepend '<subheader> ' to Activity for rows in the day range."""
        subheader = self.subheader_var.get().strip()
        if not subheader:
            messagebox.showwarning("Add subheader", "Enter a subheader first.")
            return
        start = min(self.subheader_from_var.get(), self.subheader_to_var.get())
        end = max(self.subheader_from_var.get(), self.subheader_to_var.get())
        for i, row in enumerate(self.rows, start=1):
            if i < start or i > end:
                continue
            if row.off_var.get() or row.skip_var.get():
                continue
            row.set_activity(f"{subheader} {row.get_activity()}".rstrip())

    # ---- import / export -------------------------------------------------
    def collect(self) -> list[dict[str, str] | None]:
        return [r.to_entry() for r in self.rows]

    def load_json(self) -> None:
        path = filedialog.askopenfilename(
            filetypes=[("JSON", "*.json"), ("All", "*.*")]
        )
        if not path:
            return
        data = json.loads(Path(path).read_text(encoding="utf-8"))
        self.days_var.set(len(data))
        self.rebuild_rows()
        for row, entry in zip(self.rows, data):
            row.load(entry)
        self._lock_sundays()

    def import_excel(self) -> None:
        path = filedialog.askopenfilename(
            filetypes=[("Excel", "*.xlsx"), ("All", "*.*")]
        )
        if not path:
            return
        try:
            start_weekday, entries = parse_timesheet_excel(path)
        except Exception as e:
            messagebox.showerror("Import failed", str(e))
            return
        if not entries:
            messagebox.showwarning(
                "Import Excel",
                f"No data rows found starting at row {TIMESHEET_DATA_START_ROW}.",
            )
            return

        self.days_var.set(len(entries))
        self.start_var.set(start_weekday)
        self.rebuild_rows()
        for row, entry in zip(self.rows, entries):
            row.load(entry)
        self._lock_sundays()
        messagebox.showinfo(
            "Imported", f"Imported {len(entries)} rows from {Path(path).name}."
        )

    def save_json(self) -> None:
        path = filedialog.asksaveasfilename(
            defaultextension=".json",
            filetypes=[("JSON", "*.json")],
        )
        if not path:
            return
        Path(path).write_text(
            json.dumps(self.collect(), indent=2, ensure_ascii=False),
            encoding="utf-8",
        )
        messagebox.showinfo("Saved", f"Saved {path}")

    def generate(self) -> None:
        # Sundays have no button on the site (auto-OFF), so drop them here to
        # keep entries[] aligned with the buttons the page actually renders.
        rows = [r for r in self.rows if r.weekday != "Sun"]
        skipped_sundays = len(self.rows) - len(rows)
        entries = [r.to_entry() for r in rows]
        entries_json = json.dumps(entries, indent=4, ensure_ascii=False)
        script = SCRIPT_TEMPLATE.format(entries_json=entries_json)

        out = Path(__file__).with_name("script.generated.js")
        out.write_text(script, encoding="utf-8")

        self.root.clipboard_clear()
        self.root.clipboard_append(script)
        messagebox.showinfo(
            "Generated",
            f"Wrote {out.name} and copied script to clipboard.\n"
            f"{len(entries)} rows ({skipped_sundays} Sundays excluded — "
            f"no button on site).",
        )


def main() -> None:
    root = tk.Tk()
    App(root)
    root.geometry("1000x680")
    root.mainloop()


if __name__ == "__main__":
    main()
